/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fula_constructor_s.a.s;

/**
 *
 * @author Administrator
 */
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
public class ApprovalEvidence extends javax.swing.JFrame {

    /**
     * Creates new form ApprovalEvidence
     */
    public ApprovalEvidence() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        ButtonVolver = new javax.swing.JButton();
        ButtonBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        informsPanel = new javax.swing.JPanel();
        Logotipo = new javax.swing.JLabel();
        InformeNumberForInformBttn = new javax.swing.JRadioButton();
        clientNameForInformBttn = new javax.swing.JRadioButton();
        searchInformeTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonVolver.setText("Volver");
        ButtonVolver.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 0, 0)));
        ButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVolverActionPerformed(evt);
            }
        });

        ButtonBuscar.setForeground(new java.awt.Color(153, 0, 102));
        ButtonBuscar.setText("Buscar");
        ButtonBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102)));
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setText("Buscado por:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(125, 21, 73));
        jLabel7.setText("Aprobación de Informes");

        informsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102)));

        javax.swing.GroupLayout informsPanelLayout = new javax.swing.GroupLayout(informsPanel);
        informsPanel.setLayout(informsPanelLayout);
        informsPanelLayout.setHorizontalGroup(
            informsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        informsPanelLayout.setVerticalGroup(
            informsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        buttonGroup1.add(InformeNumberForInformBttn);
        InformeNumberForInformBttn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        InformeNumberForInformBttn.setText("Número de informe");
        InformeNumberForInformBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformeNumberForInformBttnActionPerformed(evt);
            }
        });

        buttonGroup1.add(clientNameForInformBttn);
        clientNameForInformBttn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clientNameForInformBttn.setText("Nombre del Cliente");
        clientNameForInformBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientNameForInformBttnActionPerformed(evt);
            }
        });

        searchInformeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInformeTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Logotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(clientNameForInformBttn))
                                            .addComponent(InformeNumberForInformBttn, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(30, 30, 30)
                                        .addComponent(searchInformeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(informsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Logotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(clientNameForInformBttn))
                        .addGap(6, 6, 6)
                        .addComponent(InformeNumberForInformBttn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchInformeTxt)
                            .addComponent(ButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(informsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVolverActionPerformed
        // TODO add your handling code here:
        AdminView view=new AdminView();
        view.setVisible(true);
        this.hide();
    }//GEN-LAST:event_ButtonVolverActionPerformed

    private void InformeNumberForInformBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformeNumberForInformBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InformeNumberForInformBttnActionPerformed

    private void clientNameForInformBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientNameForInformBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientNameForInformBttnActionPerformed

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        // TODO add your handling code here:
        // Obtener el texto ingresado en el JTextField
        String searchValue = searchInformeTxt.getText().trim();

        // Verificar cuál radio button está seleccionado
        if (clientNameForInformBttn.isSelected()) {
            // Si está seleccionado clientNameForInformBttn
            revisarArchivos("client", searchValue);

        } else if (InformeNumberForInformBttn.isSelected()) {
            // Si está seleccionado InformeNumberForInformBttn
            revisarArchivos("informe", searchValue);
        }
    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void searchInformeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInformeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInformeTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApprovalEvidence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApprovalEvidence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApprovalEvidence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApprovalEvidence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApprovalEvidence().setVisible(true);
            }
        });
    }
    
    private void revisarArchivos(String tipoBusqueda, String searchValue) {
        // Ruta a la carpeta que contiene los archivos
        File carpeta = new File("C:\\Users\\Windows\\Documents\\NetBeansProjects\\FULA_CONSTRUCTOR_S.A.S\\informes");
        
        // Verificar que la carpeta exista
        if (carpeta.isDirectory()) {
            // Obtener la lista de archivos en la carpeta
            
            File[] archivos = carpeta.listFiles((dir, name) -> name.endsWith(".txt"));
            // Revisar cada archivo en la carpeta
            for (File archivo : archivos) {
                
                // Dividir el nombre del archivo por el guión bajo
                String[] lineSplit = archivo.getName().split("_");
                //["informe",numInforme,Cliente,".txt"]
                System.out.println("Leyendo archivo: " +lineSplit[1]+" "+lineSplit[2]);
                // Verificar la condición según el tipo de búsqueda
                if (tipoBusqueda.equals("client")) {
                    // Revisar el tercer valor del nombre del archivo
                    
                    
                    if (lineSplit.length > 2 && lineSplit[2].equals(searchValue)) {
                        //querre agregar este archivo al jPanel que los contiene
                        
                        leerYProcesarArchivo(archivo, lineSplit[1], lineSplit[2]);
                    }
                } else if (tipoBusqueda.equals("informe")) {
                    
                    //"Informe # "+lineSplit[1]+" de "+lineSplit[2]
                    if (lineSplit.length > 1 && lineSplit[1].equals(searchValue)) {
                        //querre agregar este archivo al jPanel que los contiene
                        leerYProcesarArchivo(archivo, lineSplit[1], lineSplit[2]);
                    }
                }
            }
        } else {
            System.out.println("La carpeta especificada no existe.");
        }
    }
    private void leerYProcesarArchivo(File archivo, String numeroInforme, String nombreCliente) {
        try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
            informsPanel.removeAll();  
            // Leer solo la primera línea del archivo
            String linea = br.readLine(); 

            // Verificar si se ha leído una línea
            if (linea != null) {
                // Dividir el contenido de la línea usando '|'
                String[] contenidoSplit = linea.split("\\|");

                // Verificar si el array tiene exactamente 10 elementos (para que contenidoSplit[9] exista)
                System.out.println("Tamaño del split: " + contenidoSplit.length);
                if (contenidoSplit.length == 10) {
                    // Verificar si contenidoSplit[9] es igual a 'SV'
                    
                    if (contenidoSplit[9].equals("SV")) {
                        // Crear un JLabel con la información
                        JLabel lblService = new JLabel("Informe # " + numeroInforme + " de " + nombreCliente + " (No validado)");

                        // Asegurar que informsPanel tenga un layout que permita añadir componentes
                        informsPanel.setLayout(new BoxLayout(informsPanel, BoxLayout.Y_AXIS));

                        // Agregar el JLabel al JPanel
                        informsPanel.add(lblService);

                        // Actualizar el JPanel
                        informsPanel.revalidate();
                        informsPanel.repaint();
                    }
                } else {
                    System.out.println("La línea no contiene exactamente 10 elementos: " + linea);
                }
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonVolver;
    private javax.swing.JRadioButton InformeNumberForInformBttn;
    private javax.swing.JLabel Logotipo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton clientNameForInformBttn;
    private javax.swing.JPanel informsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField searchInformeTxt;
    // End of variables declaration//GEN-END:variables
}
