/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fula_constructor_s.a.s;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.RandomAccessFile;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class ClientCreation extends javax.swing.JFrame {

    /**
     * Creates new form ClientCreation
     */
    public ClientCreation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        clientNameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        clientSocialReasonTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        clientDirectionTxt = new javax.swing.JTextField();
        createClientBttn = new javax.swing.JButton();
        backClientBttn = new javax.swing.JButton();
        clientEmailTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        clientIdTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Creacion de clientes");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Razón social:");

        jLabel4.setText("Direccion:");

        createClientBttn.setText("Crear cliente");
        createClientBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createClientBttnActionPerformed(evt);
            }
        });

        backClientBttn.setText("Volver");
        backClientBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backClientBttnActionPerformed(evt);
            }
        });

        jLabel5.setText("Correo electronico:");

        jLabel6.setText("Identificacion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clientSocialReasonTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(clientDirectionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(clientEmailTxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clientNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(createClientBttn)
                        .addGap(18, 18, 18)
                        .addComponent(backClientBttn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(clientNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(clientSocialReasonTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(clientDirectionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createClientBttn)
                    .addComponent(backClientBttn))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void AddLine(String clientName,String clientId,String clientDirection,String clientSocialReason,String clientEmail){
        try(FileWriter fw = new FileWriter("clients.txt",true)){
            PrintWriter pw = new PrintWriter(fw);
            pw.println(clientId+";"+clientName+";"+clientSocialReason+";"+clientEmail+";"+clientDirection);
        }catch (IOException e){
            
        }
    }
    private void createClientBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createClientBttnActionPerformed
        // TODO add your handling code here:
        String clientName = clientNameTxt.getText();
        String clientId = clientIdTxt.getText();
        String clientDirection = clientDirectionTxt.getText();
        String clientSocialReason= clientSocialReasonTxt.getText();
        String clientEmail = clientEmailTxt.getText();
        
        
        
        if (!clientName.isEmpty() && !clientId.isEmpty() && !clientDirection.isEmpty()&& !clientSocialReason.isEmpty()&& !clientEmail.isEmpty()) {
            RandomAccessFile raf = null; 
            try {
                String clientString;//fila de la base de datos
               //id;nombre;razonsocial;email;direccion



                // Using file pointer creating the file->debe ser modificada 
                File file = new File("C:\\Users\\Windows\\Documents\\NetBeansProjects\\FULA_CONSTRUCTOR_S.A.S\\clients.txt");

                if (!file.exists()) {

                    // Create a new file if not exists.
                    file.createNewFile();
                }



                // Opening file in reading and write mode.
                raf = new RandomAccessFile(file, "rw");
                boolean clientExists = false;
                // Traversing the file
                // getFilePointer() give the current offset
                // value from start of the file.
                while (raf.getFilePointer() < raf.length()) {

                    // reading line from the file.
                    clientString = raf.readLine();

                    // splitting the string to get name and
                    // number
                    String[] lineSplit = clientString.split(";");

                    // separating name and number.

                    if (lineSplit[0].equals(clientId)){
                        JOptionPane.showMessageDialog(null, "Ya hay un cliente registrado con esta identificacion.");
                        clientExists=true;
                        break;
                    }
                }
                if(!clientExists){
                    AddLine(clientName,clientId,clientDirection,clientSocialReason,clientEmail);
                    JOptionPane.showMessageDialog(null, "Cliente creado correctamente");
                }
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error al escribir en el archivo: " + e.getMessage());
                e.printStackTrace(); // Opcional: para más detalles en la consola
            } finally {
            // Cerrar el archivo en el bloque finally para asegurar que se cierre
                if (raf != null) {
                    try {
                        raf.close();
                    } catch (IOException e) {
                        System.out.println("Error al cerrar el archivo: " + e.getMessage());
                    }
                }
            }

            
        }else{
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
        }
    }//GEN-LAST:event_createClientBttnActionPerformed

    private void backClientBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backClientBttnActionPerformed
        // TODO add your handling code here:
        UsersView view = new UsersView();
        view.setVisible(true);
        this.hide();
    }//GEN-LAST:event_backClientBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientCreation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backClientBttn;
    private javax.swing.JTextField clientDirectionTxt;
    private javax.swing.JTextField clientEmailTxt;
    private javax.swing.JTextField clientIdTxt;
    private javax.swing.JTextField clientNameTxt;
    private javax.swing.JTextField clientSocialReasonTxt;
    private javax.swing.JButton createClientBttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
