/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fula_constructor_s.a.s;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.RandomAccessFile;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class ClientCreation extends javax.swing.JFrame {

    private String name, id, address, nameEmp, email;

    public ClientCreation() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        clientIdTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        clientSocialReasonTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        clientDirectionTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        clientEmailTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        createClientBttn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBack = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(0, 4, 12, 5));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(150, 17, 52));
        jLabel6.setText("Identificación:");
        jPanel1.add(jLabel6);

        clientIdTxt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        clientIdTxt.setForeground(new java.awt.Color(150, 17, 52));
        jPanel1.add(clientIdTxt);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(150, 17, 52));
        jLabel3.setText("Razón social:");
        jPanel1.add(jLabel3);

        clientSocialReasonTxt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        clientSocialReasonTxt.setForeground(new java.awt.Color(150, 17, 52));
        jPanel1.add(clientSocialReasonTxt);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(150, 17, 52));
        jLabel4.setText("Dirección:");
        jPanel1.add(jLabel4);

        clientDirectionTxt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        clientDirectionTxt.setForeground(new java.awt.Color(150, 17, 52));
        jPanel1.add(clientDirectionTxt);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(150, 17, 52));
        jLabel5.setText("Correo electrónico:");
        jPanel1.add(jLabel5);

        clientEmailTxt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        clientEmailTxt.setForeground(new java.awt.Color(150, 17, 52));
        jPanel1.add(clientEmailTxt);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(150, 17, 52));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrador de clientes");

        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 12, 0));

        createClientBttn.setBackground(new java.awt.Color(255, 254, 255));
        createClientBttn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        createClientBttn.setForeground(new java.awt.Color(150, 17, 52));
        createClientBttn.setText("Guardar");
        createClientBttn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(150, 17, 52), 2, true));
        createClientBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createClientBttnActionPerformed(evt);
            }
        });
        jPanel2.add(createClientBttn);

        jButton1.setBackground(new java.awt.Color(255, 254, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(150, 17, 52));
        jButton1.setText("Buscar");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(150, 17, 52), 2, true));
        jPanel2.add(jButton1);

        menuBack.setText("Salir");
        menuBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBackMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuBack);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void AddLine(String clientId, String clientDirection, String clientSocialReason, String clientEmail) {
        try (FileWriter fw = new FileWriter("Clientes/clientes.txt", true)) {
            PrintWriter pw = new PrintWriter(fw);
            pw.println(clientId + ";" + clientSocialReason + ";" + clientEmail + ";" + clientDirection);
        } catch (IOException e) {

        }
    }

    private void setInfo() {
        id = clientIdTxt.getText();
        address = clientDirectionTxt.getText();
        nameEmp = clientSocialReasonTxt.getText();
        email = clientEmailTxt.getText();
    }
    
    private void eraser(){
        clientIdTxt.setText("");
        clientDirectionTxt.setText("");
        clientSocialReasonTxt.setText("");
        clientEmailTxt.setText("");
    }

    private void saveCliente() {
        this.setInfo();

        if (!id.isEmpty() && !address.isEmpty() && !nameEmp.isEmpty() && !email.isEmpty()) {
            RandomAccessFile raf = null;
            try {
                String clientString;//fila de la base de datos
                //id;nombre;razonsocial;email;direccion

                // Using file pointer creating the file->debe ser modificada 
                File file = new File("Clientes/clientes.txt");

                if (!file.exists()) {

                    // Create a new file if not exists.
                    file.createNewFile();
                }

                // Opening file in reading and write mode.
                raf = new RandomAccessFile(file, "rw");
                boolean clientExists = false;
                // Traversing the file
                // getFilePointer() give the current offset
                // value from start of the file.
                while (raf.getFilePointer() < raf.length()) {

                    // reading line from the file.
                    clientString = raf.readLine();

                    // splitting the string to get name and
                    // number
                    String[] lineSplit = clientString.split(";");

                    // separating name and number.
                    if (lineSplit[0].equals(id)) {
                        JOptionPane.showMessageDialog(null, "Ya hay un cliente registrado con esta identificación.");
                        clientExists = true;
                        break;
                    }
                }
                if (!clientExists) {
                    AddLine(id, address, nameEmp, email);
                    JOptionPane.showMessageDialog(null, "Cliente creado correctamente");
                    eraser();
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error al escribir en el archivo: " + e.getMessage());
                e.printStackTrace(); // Opcional: para más detalles en la consola
            } finally {
                // Cerrar el archivo en el bloque finally para asegurar que se cierre
                if (raf != null) {
                    try {
                        raf.close();
                    } catch (IOException e) {
                        System.out.println("Error al cerrar el archivo: " + e.getMessage());
                    }
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
        }
    }

    private void createClientBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createClientBttnActionPerformed
        // TODO add your handling code here:
        this.saveCliente();
    }//GEN-LAST:event_createClientBttnActionPerformed

    private void menuBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBackMouseClicked
        // TODO add your handling code here:
        UsersView view = new UsersView();
        view.setVisible(true);
        this.hide();
    }//GEN-LAST:event_menuBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientCreation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clientDirectionTxt;
    private javax.swing.JTextField clientEmailTxt;
    private javax.swing.JTextField clientIdTxt;
    private javax.swing.JTextField clientSocialReasonTxt;
    private javax.swing.JButton createClientBttn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu menuBack;
    // End of variables declaration//GEN-END:variables
}
