/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fula_constructor_s.a.s;

/**
 *
 * @author Windows
 */
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.io.*;
import javax.swing.JFileChooser;
import java.util.ArrayList;
import java.util.List;
import java.io.File;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
public class frontInformes extends javax.swing.JFrame {

    /**
     * Creates new form frontInformes
     */
    public frontInformes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        dateStartWork = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        dateFinishWork = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaJustifyWork = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        socialReasonTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        saveClientBttn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        responsableNameTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        workDirectionTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        workIdTxt = new javax.swing.JTextField();
        chargeEvidencesBttn = new javax.swing.JButton();
        loggOutBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Fecha inicio de obra:");

        jLabel2.setText("Fecha finalización obra:");

        jLabel3.setText("Justificación de la obra:");

        textAreaJustifyWork.setColumns(20);
        textAreaJustifyWork.setRows(5);
        jScrollPane1.setViewportView(textAreaJustifyWork);

        jLabel4.setText("Razón social:");

        socialReasonTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socialReasonTxtActionPerformed(evt);
            }
        });

        jLabel5.setText("Dirección de obra:");

        saveClientBttn.setText("Guardar cliente");
        saveClientBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveClientBttnActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombre del responsable:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Crear informe de obra");

        jLabel8.setText("Correo electrónico:");

        jLabel9.setText("Identificación (NIT/CC):");

        chargeEvidencesBttn.setText("Cargar evidencias");
        chargeEvidencesBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargeEvidencesBttnActionPerformed(evt);
            }
        });

        loggOutBttn.setText("Volver");
        loggOutBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loggOutBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(148, 148, 148))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(107, 107, 107)
                        .addComponent(emailTxt))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(112, 112, 112)
                        .addComponent(workDirectionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(83, 83, 83)
                        .addComponent(workIdTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(140, 140, 140)
                        .addComponent(socialReasonTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(84, 84, 84))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chargeEvidencesBttn)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(saveClientBttn))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(loggOutBttn)))
                                .addGap(76, 76, 76)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dateStartWork, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateFinishWork, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(responsableNameTxt)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateStartWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(dateFinishWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(responsableNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(workIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(socialReasonTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(workDirectionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(chargeEvidencesBttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveClientBttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loggOutBttn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void socialReasonTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socialReasonTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_socialReasonTxtActionPerformed
    private List<File> selectedImages = new ArrayList<>(); // Lista para guardar las imágenes seleccionadas

    public void AddLine(String workDirection, String email, String responsableName, String socialReason, String FinishDateText,
                    String StartDateText, String workId, String workJustification) {
        String folderPath = "C:\\Users\\Windows\\Documents\\NetBeansProjects\\FULA_CONSTRUCTOR_S.A.S\\informes"; // Cambia esta ruta según tu carpeta

        File folder = new File(folderPath);

        // Verifica que la ruta sea una carpeta válida
        if (!folder.exists() || !folder.isDirectory()) {
            JOptionPane.showMessageDialog(this, "La carpeta especificada no existe o no es un directorio.");
            return; // Termina la ejecución si la carpeta no es válida
        }

        // Define el nombre del archivo dentro de la carpeta existente
        
        LocalDate hoy = LocalDate.now();
        
        DateTimeFormatter format2 = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String filename = folderPath + "/Informe_" + responsableName + ".txt";
        try (FileWriter fw = new FileWriter(filename, true)) {
            PrintWriter pw = new PrintWriter(fw);

            // Construir la cadena con las rutas de las imágenes seleccionadas
            StringBuilder imagePaths = new StringBuilder();
            for (File image : selectedImages) {
                imagePaths.append(image.getAbsolutePath()).append(";");
            }

            // Si hay rutas de imágenes, eliminar el último separador ";"
            if (imagePaths.length() > 0) {
                imagePaths.setLength(imagePaths.length() - 1); // Quita el último ";"
            }

            // Escribir los datos en una sola línea junto con las rutas de las imágenes
            pw.println(responsableName + ";" + workId + ";" + email + ";" + socialReason + ";" + workDirection + ";" + 
                       StartDateText + ";" + FinishDateText + ";" + workJustification + ";" + imagePaths.toString());
            JOptionPane.showMessageDialog(this, "Cliente y evidencias guardados correctamente.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar los datos del cliente o las evidencias.");
            e.printStackTrace();
        }
    }
    private void saveClientBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveClientBttnActionPerformed
        // TODO add your handling code here:
        String workDirection = workDirectionTxt.getText();
        String email = emailTxt.getText();
        String responsableName = responsableNameTxt.getText();
        String socialReason = socialReasonTxt.getText();
        String workId=workIdTxt.getText();
        Date selectedFinishDate = dateFinishWork.getDate();
        Date selectedStartDate = dateStartWork.getDate();// Obtiene la fecha seleccionada
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // Define el formato de la fecha
        String FinishDateText = dateFormat.format(selectedFinishDate);
        String StartDateText = dateFormat.format(selectedStartDate);
        String workJustification=textAreaJustifyWork.getText();
        
        if (!workDirection.isEmpty() && !email.isEmpty() && !responsableName.isEmpty() && !socialReason.isEmpty()
             && !FinishDateText.isEmpty() && !StartDateText.isEmpty() && !workId.isEmpty() && !workJustification.isEmpty()) {
            // Verificar si se han seleccionado imágenes antes de llamar a AddLine
            if (selectedImages.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe cargar evidencias antes de guardar el cliente.");
            } else {
                AddLine(workDirection, email, responsableName, socialReason, FinishDateText, StartDateText, workId, workJustification);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos.");
        }

        
    }//GEN-LAST:event_saveClientBttnActionPerformed

    private void chargeEvidencesBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargeEvidencesBttnActionPerformed
        // TODO add your handling code here:
        // Crear JFileChooser para seleccionar imágenes
        JFileChooser getImage = new JFileChooser();
        getImage.setMultiSelectionEnabled(true);
        getImage.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imágenes (jpg, jpeg, png, gif)", 
                "jpg", "jpeg", "png", "gif"));

        // Mostrar el diálogo de selección de archivos
        if (getImage.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            // Guardar las imágenes seleccionadas en la lista
            File[] images = getImage.getSelectedFiles();
            selectedImages.clear(); // Limpiar la lista antes de agregar nuevas imágenes
            for (File image : images) {
                selectedImages.add(image);
            }
            JOptionPane.showMessageDialog(this, "Imágenes seleccionadas correctamente.");
        }
    }//GEN-LAST:event_chargeEvidencesBttnActionPerformed

    private void loggOutBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loggOutBttnActionPerformed
        // TODO add your handling code here:
        UsersView view = new UsersView();
        view.setVisible(true);
        this.hide();
    }//GEN-LAST:event_loggOutBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frontInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frontInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frontInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frontInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frontInformes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chargeEvidencesBttn;
    private com.toedter.calendar.JDateChooser dateFinishWork;
    private com.toedter.calendar.JDateChooser dateStartWork;
    private javax.swing.JTextField emailTxt;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loggOutBttn;
    private javax.swing.JTextField responsableNameTxt;
    private javax.swing.JButton saveClientBttn;
    private javax.swing.JTextField socialReasonTxt;
    private javax.swing.JTextArea textAreaJustifyWork;
    private javax.swing.JTextField workDirectionTxt;
    private javax.swing.JTextField workIdTxt;
    // End of variables declaration//GEN-END:variables
}
