/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fula_constructor_s.a.s;

import java.awt.Image;
import java.awt.event.ActionEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


/**
 *
 * @author Windows
 */
public class UsersView extends javax.swing.JFrame {
    
    private ImageIcon image;
    private Icon icon;
    private String userName;
    
    /**
     *
     */
    public UsersView() {
        initComponents();
        this.setResizable(false);
    }

    /**
     *
     * @param UserName
     */
    public UsersView(String UserName) {
        this.userName = UserName;
        initComponents();
        this.setResizable(false);
        this.setLogo(imgLogo, "src\\main\\java\\com\\mycompany\\fula_constructor_s\\a\\s\\img/Recurso 2.png");
        lblUserName.setText(UserName);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        paneControl = new javax.swing.JPanel();
        btnCreateInforme = new javax.swing.JButton();
        btnVerInforme = new javax.swing.JButton();
        btnAdminClient = new javax.swing.JButton();
        btnSoporte = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuLogOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 228, 228));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(150, 17, 52));
        jLabel2.setText("FULA CONSTRUCTOR SAS");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(150, 17, 52));
        jLabel3.setText("901224360-7");

        lblUserName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(150, 17, 52));
        lblUserName.setText("userName");

        paneControl.setLayout(new java.awt.GridLayout(0, 3, 12, 12));

        btnCreateInforme.setBackground(new java.awt.Color(255, 254, 255));
        btnCreateInforme.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCreateInforme.setForeground(new java.awt.Color(150, 17, 52));
        btnCreateInforme.setText("Crear Informe");
        btnCreateInforme.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(150, 17, 52), 3, true));
        btnCreateInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateInformeActionPerformed(evt);
            }
        });
        paneControl.add(btnCreateInforme);

        btnVerInforme.setBackground(new java.awt.Color(255, 254, 255));
        btnVerInforme.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnVerInforme.setForeground(new java.awt.Color(150, 17, 52));
        btnVerInforme.setText("Ver informes");
        btnVerInforme.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(150, 17, 52), 3, true));
        paneControl.add(btnVerInforme);

        btnAdminClient.setBackground(new java.awt.Color(255, 254, 255));
        btnAdminClient.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAdminClient.setForeground(new java.awt.Color(150, 17, 52));
        btnAdminClient.setText("Administrador de Clientes");
        btnAdminClient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(150, 17, 52), 3, true));
        btnAdminClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminClientActionPerformed(evt);
            }
        });
        paneControl.add(btnAdminClient);

        btnSoporte.setBackground(new java.awt.Color(255, 254, 255));
        btnSoporte.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSoporte.setForeground(new java.awt.Color(150, 17, 52));
        btnSoporte.setText("Soporte");
        btnSoporte.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(150, 17, 52), 3, true));
        btnSoporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoporteActionPerformed(evt);
            }
        });
        paneControl.add(btnSoporte);

        menuLogOut.setText("Cerrar sesión");
        menuLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogOutMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuLogOut);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(474, 474, 474)
                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(paneControl, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(lblUserName))
                    .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(paneControl, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStateInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStateInformeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnStateInformeActionPerformed

    private void btnSearchInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchInformeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchInformeActionPerformed

    private void btnClientCreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientCreationActionPerformed
        // TODO add your handling code here:
        ClientCreation viewClienteCreation = new ClientCreation();
        viewClienteCreation.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnClientCreationActionPerformed

    private void btnNewInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewInformeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnNewInformeActionPerformed

    private void menuLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogOutMouseClicked
        // TODO add your handling code here:
        front view = new front();
        view.setVisible(true);
        this.hide();
    }//GEN-LAST:event_menuLogOutMouseClicked
   

    private void btnCreateClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateClientActionPerformed

    private void btnCreateInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateInformeActionPerformed
        // TODO add your handling code here:
        frontInformes viewInformes = new frontInformes(this.userName);
        viewInformes.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnCreateInformeActionPerformed

    private void btnSoporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoporteActionPerformed
        // TODO add your handling code here:
        SupportView view = new SupportView();
        view.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnSoporteActionPerformed

    private void btnAdminClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminClientActionPerformed
        // TODO add your handling code here:
        ClientCreation view = new ClientCreation();
        view.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnAdminClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersView().setVisible(true);
            }
        });
    }
    
    private void setLogo(JLabel img,String root){
        this.image = new ImageIcon(root);
        this.icon = new ImageIcon(this.image.getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_SMOOTH));
        img.setIcon(this.icon);
        //this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminClient;
    private javax.swing.JButton btnCreateInforme;
    private javax.swing.JButton btnSoporte;
    private javax.swing.JButton btnVerInforme;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JMenu menuLogOut;
    private javax.swing.JPanel paneControl;
    // End of variables declaration//GEN-END:variables
}
